from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import os
import uuid

def generate_pdf(data, output_path):
    """
    Generates a simple PDF from provided data.
    """
    if data.get("simulate_failure"):
        raise Exception("Simulated PDF generation failure")
        
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, height - 100, "Financial Document")
    
    c.setFont("Helvetica", 12)
    y_position = height - 140
    
    for key, value in data.items():
        c.drawString(100, y_position, f"{key}: {value}")
        y_position -= 20
        
    c.drawString(100, y_position - 40, "Generated by Bulk PDF Service BulkPDFGenerationSystem")
    
    c.showPage()
    c.save()
    return output_path
